### ISSUE TITLE
License, Fork, and Maintenance

### ISSUE THREAD

**Issue by btholt** [chrisyuska/auto-email#3]
Hey,

Sorry to inundate you with issues, but we'd like to use my fork of this repository commercially. Furthermore, we'd like to open source my fork under the redditgifts repository and maintain it.

However, your repository lacks a license. By default, you retain copyright if no license is stated. Would you consider adding a license to the project? I'd recommend the MIT License. [Here's a link to describe the varying license](http://www.codinghorror.com/blog/2007/04/pick-a-license-any-license.html).

Thanks.

**Comment by chrisyuska** [comment]
Yeah, I've been busy, so I'm sorry I haven't been of much contribution.  I appreciate your consideration though.  I'll try to add an MIT license tomorrow.
